In [1]:
import numpy as np

In [2]:
np.ones((4, 4), int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [3]:
np.full(4, 5, float)

array([5., 5., 5., 5.])

In [4]:
sonuc=np.random.normal(10, 5,  (4, 5)) # Birincisi ortalaması 10 olan standart sapması 5 olan 5x4 boyutunda random sayılar oluşturur.
sonuc

array([[12.91949456,  7.35695686, 11.98031454,  8.04008019, 10.58102518],
       [ 6.18929758,  5.55155443, 10.53403791,  8.23637897,  7.31247555],
       [ 5.01707499, 15.65201638,  5.16638493, 16.20193316, 12.77501293],
       [ 9.44163476, 10.90067548,  8.01800295, 13.46369907,  7.65555122]])

In [5]:
sonuc.shape

(4, 5)

In [6]:
dizi=np.random.randint(0, 100, ( 4, 4))

In [7]:
dizi

array([[51, 72, 29, 19],
       [ 9, 63, 26, 33],
       [46, 79, 80, 37],
       [ 9, 78, 36, 53]])

In [8]:
dizi[0:3, 0:3]

array([[51, 72, 29],
       [ 9, 63, 26],
       [46, 79, 80]])

In [9]:
dizi=[1, 2, 3, 4, 5]
dizi=np.array([dizi])
dizi

array([[1, 2, 3, 4, 5]])

In [10]:
dizi.mean()
dizi.var()
dizi.sum()

15

In [11]:
import pandas as pd

In [12]:
dizi=[1, 5, 3, 4, 5, 6]
dizi=pd.Series(dizi)

In [13]:
type(dizi) 

pandas.core.series.Series

In [14]:
dizi.axes

[RangeIndex(start=0, stop=6, step=1)]

In [15]:
dizi.ndim

1

In [16]:
dizi.size

6

In [17]:
dizi.shape

(6,)

In [1]:
import pandas as pd

In [24]:
pd.Series([1, 2, 3, 4, 5, 6])

seri_1=pd.Series([1, 2, 3, 4, 5, 6], index=["2", "4", "6", "8", "0", "1"])

In [25]:
seri_2=pd.Series([1, 2, 3, 4, 5, 6], index=["2", "4", "6", "8", "0", "1"])

In [26]:
pd.concat([seri_1, seri_2])

2    1
4    2
6    3
8    4
0    5
1    6
2    1
4    2
6    3
8    4
0    5
1    6
dtype: int64

In [27]:
import numpy as np 
import pandas as pd

In [28]:
np_array=np.random.randint(0, 10, 10)

In [29]:
sonuc=pd.Series(np_array, index=["a", "b", "c", "d", "e", "f", "g", "h", "j", "k" ])
type(sonuc)

pandas.core.series.Series

In [30]:
sonuc.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'j', 'k'], dtype='object')

In [31]:
sonuc.keys

<bound method Series.keys of a    2
b    5
c    0
d    3
e    9
f    3
g    7
h    6
j    9
k    5
dtype: int64>

In [30]:
key="z"
if key in sonuc:
    print(sonuc[key])
if key not in sonuc:
    print(f"{key} not in sonuc of Seris")

z not in sonuc of Seris


In [58]:
sonuc["a"]
np_array=np.arange(1, 51)
np_array=np_array.reshape(10, 5)

In [59]:
frame=pd.DataFrame(np_array, columns=["Degisken ismi1", "Degisken ismi2", "Degisken ismi3", "Degisken ismi4", "Degisken ismi5"])

In [60]:
frame.axes

[RangeIndex(start=0, stop=10, step=1),
 Index(['Degisken ismi1', 'Degisken ismi2', 'Degisken ismi3', 'Degisken ismi4',
        'Degisken ismi5'],
       dtype='object')]

In [61]:
frame.ndim

2

In [62]:
frame.size

50

In [63]:
frame.head()

Degisken ismi1  Degisken ismi2  Degisken ismi3  Degisken ismi4  \
0               1               2               3               4   
1               6               7               8               9   
2              11              12              13              14   
3              16              17              18              19   
4              21              22              23              24   

   Degisken ismi5  
0               5  
1              10  
2              15  
3              20  
4              25

In [64]:
frame.tail()

Degisken ismi1  Degisken ismi2  Degisken ismi3  Degisken ismi4  \
5              26              27              28              29   
6              31              32              33              34   
7              36              37              38              39   
8              41              42              43              44   
9              46              47              48              49   

   Degisken ismi5  
5              30  
6              35  
7              40  
8              45  
9              50

In [66]:
m=np.random.randint(1, 30, (10, 3))
n=pd.DataFrame(m, columns=["Var_1", "Var_2", "Var_3"])
n

Var_1  Var_2  Var_3
0     11      6      5
1     20     18      7
2      6     13     29
3     23     15     14
4     22      2      6
5     26     29     19
6     14     14      7
7     13     14     10
8     28     16     29
9     10     26     24

In [75]:
n[["Var_1"]][0:3]

Var_1
0     11
1     20
2      6

In [76]:
n.Var_1

0    11
1    20
2     6
3    23
4    22
5    26
6    14
7    13
8    28
9    10
Name: Var_1, dtype: int32

In [83]:
n[(n.Var_1>10) & (n.Var_1<20)]

Var_1  Var_2  Var_3
0     11      6      5
6     14     14      7
7     13     14     10

In [88]:
a = n + 10
a

Var_1  Var_2  Var_3
0     21     16     15
1     30     28     17
2     16     23     39
3     33     25     24
4     32     12     16
5     36     39     29
6     24     24     17
7     23     24     20
8     38     26     39
9     20     36     34

In [89]:
n

Var_1  Var_2  Var_3
0     11      6      5
1     20     18      7
2      6     13     29
3     23     15     14
4     22      2      6
5     26     29     19
6     14     14      7
7     13     14     10
8     28     16     29
9     10     26     24

In [92]:
pd_concat=pd.concat([a, n])
pd_concat

Var_1  Var_2  Var_3
0     21     16     15
1     30     28     17
2     16     23     39
3     33     25     24
4     32     12     16
5     36     39     29
6     24     24     17
7     23     24     20
8     38     26     39
9     20     36     34
0     11      6      5
1     20     18      7
2      6     13     29
3     23     15     14
4     22      2      6
5     26     29     19
6     14     14      7
7     13     14     10
8     28     16     29
9     10     26     24

In [32]:
import numpy as np

In [34]:
x  = np.arange(1, 34)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [36]:
y = x.reshape(11, 3)
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [37]:
import pandas as pd

In [43]:
df_array = pd.DataFrame([np.random.randint(1, 34,
                                          10)])
df_array

0   1   2  3   4   5   6   7  8   9
0  3  18  26  3  10  33  12  28  4  31

In [48]:
degisken = 0
print("dshjd {} jsa".format(degisken))
print(f"dshjd {degisken} jsa")
print("dshjd %s jsa" % degisken)

dshjd 0 jsa
dshjd 0 jsa
dshjd 0 jsa
