In [7]:
# iki dizinin carpimi sonucu yeni bir dizi olusturulmasi
import numpy as np
a=[1, 3, 5, 7]
b=[0, 2, 4, 6]
ab=[ ]
for i in range(0, len(a)):
    ab.append(a[i]*b[i])
ab

[0, 6, 20, 42]

In [8]:
# iki dizinin carpimi
a = np.array([1, 3, 5, 7,  9])
b = np.array([0, 2, 4, 6, 8])
a * b

array([ 0,  6, 20, 42, 72])

In [11]:
# Degiskenin tipinin ogrenilmesi
result = np.array([1,2,3,4,5], dtype=float)
type(result)

numpy.ndarray

In [43]:
# bir kutuphane veya fonksiyonun hakkında bilgi edinilmesi
?np.array
#?np.mean

In [55]:
liste = [1, 2, 3, 4, 5]
numpy_dizi_copy = np.array(liste, dtype=float, copy=True, order='C', subok=True) # np.array dizisi olusturma
numpy_dizi_copy

array([1., 2., 3., 4., 5.])

In [57]:
# ister dtype parametresi kullan ister kullanma bir farklılık gostermemektedir.
np.zeros(10, float)      # 10 boyutunda degerleri bos olan bir dize dondurur.
np.zeros((3, 5), int)    # 3x5 boyutunda degerleri bos olan bir dize dondurur.
np.ones((3, 5))          # 3x5 boyutunda float birim matris elde eder.
np.full((3, 5), 5, int)  # 3x5 boyutunda istenilen deger ve boyutta int matris tanimlandi
np.arange(0, 33, 3)      # 0 dan 33 degerine kadar 3 artacak sekilde bir dize dondurur
np.linspace(0, 1, 10)    # 0 ve 1 degerleri arasinda 10 adet degeri paylasimli olacak sekilde bir dize olarak dondurur.
np.linspace(1, 2, 33, endpoint=False) # endpoint son sayinin dahil edilip edilmeyecegi belirtir.

array([1.     , 1.03125, 1.0625 , 1.09375, 1.125  , 1.15625, 1.1875 ,
       1.21875, 1.25   , 1.28125, 1.3125 , 1.34375, 1.375  , 1.40625,
       1.4375 , 1.46875, 1.5    , 1.53125, 1.5625 , 1.59375, 1.625  ,
       1.65625, 1.6875 , 1.71875, 1.75   , 1.78125, 1.8125 , 1.84375,
       1.875  , 1.90625, 1.9375 , 1.96875, 2.     ])

In [82]:
import numpy as np
import matplotlib.pyplot as plt

means = []
stds = []

for i in range(1, 101):
    dizi = np.random.normal(10, 5, (i, i))
    mean = np.mean(dizi)
    std = np.std(dizi)


In [65]:
np.random.randint(0, 8, (5,3))

array([[6, 0, 3],
       [4, 7, 0],
       [2, 3, 2],
       [0, 5, 3],
       [6, 7, 4]])

In [84]:
np.random.randint(10, size=5) # 0 10 arasında rastgele 5 tane deger uretir.
random_degerler = np.random.randint(0, 10, (3, 5)) # 0 10 arasında rastgele 5 tane deger uretir.

In [85]:
random_degerler.ndim # ndim dizinin boyutunu verir.

2

In [87]:
random_degerler.shape # shape satir ve sutun degerlerini yazdirir.
# Ayni sekilde farkli bir sekilde ekrana yazdirilmak istenirse. aşağıdaki kod kullanılabilir.
print(random_degerler.shape[0])
print(random_degerler.shape[1])

3
5


In [25]:
random_degerler.size # Size toplam dizi boyutunu belirler

15

In [26]:
random_degerler.dtype

dtype('int32')

In [29]:
b=np.random.randint(4,10, size=(2,4))
b

array([[6, 5, 9, 8],
       [6, 9, 8, 4]])

In [30]:
c = np.random.normal(9, 8, 15)
c

array([ 1.95716221,  8.04694538, 11.13123536, -6.42068043, 14.29597736,
       25.90165245, 16.7269951 ,  5.23932635, 10.24646912, 19.13704609,
        1.62788528,  2.87379819,  7.3626363 , 20.07480763,  8.96336698])

In [31]:
c.reshape((3, 5))

array([[ 1.95716221,  8.04694538, 11.13123536, -6.42068043, 14.29597736],
       [25.90165245, 16.7269951 ,  5.23932635, 10.24646912, 19.13704609],
       [ 1.62788528,  2.87379819,  7.3626363 , 20.07480763,  8.96336698]])

In [33]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [37]:
a,b=x,y
ab=np.concatenate([a, b])
np.concatenate([a, b, ab])

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [39]:
abc=np.random.randint(1, 100, 15)
abc

array([77, 20, 88, 26, 86, 44, 47, 36,  7, 12, 92,  7,  1, 57, 23])

In [41]:
abc.sort()
abc

array([ 1,  7,  7, 12, 20, 23, 26, 36, 44, 47, 57, 77, 86, 88, 92])

In [44]:
a=np.random.randint(0, 10, (3, 5))
a

array([[1, 5, 6, 8, 2],
       [1, 0, 8, 1, 5],
       [6, 3, 5, 5, 8]])

In [67]:
a[0,0:2,2]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed